LTO_ENABLE = yes
NKRO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
SWAP_HANDS_ENABLE = yes
COMBO_ENABLE = yes
REPEAT_KEY_ENABLE = yes
SEND_STRING_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
OLED_ENABLE = yes
WPM_ENABLE = yes
CAPS_WORD_ENABLE = yes
UNICODE_COMMON = yes
DEFERRED_EXEC_ENABLE = yes
SRC += rpn_calc.c oled.c

AUDIO_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
BACKLIGHT_ENABLE = no
MIDI_ENABLE = no
UCIS_ENABLE = no
VARIABLE_TRACE = no
KEY_LOCK_ENABLE = no
SPLIT_KEYBOARD = no
CUSTOM_MATRIX = no


