LTO_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
SLEEP_LED_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
UCIS_ENABLE = no
AUDIO_ENABLE = yes
VARIABLE_TRACE = no
KEY_LOCK_ENABLE = no
SPLIT_KEYBOARD = no
CUSTOM_MATRIX = no
DEFERRED_EXEC_ENABLE = no



