LTO_ENABLE = yes
NKRO_ENABLE = yes
KEY_OVERRIDE_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
AUDIO_ENABLE = no

CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
BACKLIGHT_ENABLE = no
MIDI_ENABLE = no
UNICODE_ENABLE = no
UCIS_ENABLE = no
VARIABLE_TRACE = no
KEY_LOCK_ENABLE = no
SPLIT_KEYBOARD = no
CUSTOM_MATRIX = no
DEFERRED_EXEC_ENABLE = no



