LTO_ENABLE = yes
NKRO_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
DYNAMIC_MACRO_ENABLE = yes
DEFERRED_EXEC_ENABLE = yes

UNICODE_ENABLE = no

KEY_OVERRIDE_ENABLE = no
AUDIO_ENABLE = no
SWAP_HANDS_ENABLE = no
OLED_ENABLE = no
WPM_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
SLEEP_LED_ENABLE = no
BACKLIGHT_ENABLE = no
MIDI_ENABLE = no
UCIS_ENABLE = no
VARIABLE_TRACE = no
KEY_LOCK_ENABLE = no
SPLIT_KEYBOARD = no
DEFERRED_EXEC_ENABLE = no
CUSTOM_MATRIX = no

